apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: brittofrancis/simple_blog_api
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"      
          ports:
            - containerPort: 5432
          env:
            - name: PORT
              value: '3000'
            - name: POSTGRES_HOST
              value: localhost
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_USERNAME
              value: postgres  
            - name: POSTGRES_DB
              value: simple_blog_api
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: password
                  key: POSTGRES_PASSWORD          
